### ISSUE TITLE
only poll beanstalkd upon scrape

### ISSUE THREAD

**Issue by marcelcorso** [messagebird/beanstalkd_exporter#12]
Don't poll beanstalkd with a timer. Actually request stats when prometheus comes scraping

**Comment by activeshadow** [comment]
FYI this seems to cause the request to take too long and Prometheus times out on `context deadline exceeded`.

**Comment by marcelcorso** [comment]
Oh dear I feared that.
On our test setup it worked fine. But maybe the whole request may take too
long if beanstalkd has many tubes: they are sequentially scraped.

There are some low hanging fruit-optimizations but maybe the real solution
is to implement somekind of whitelist/blacklist.
